### ISSUE TITLE
Graphql Example

### ISSUE THREAD

**Issue by galkatz373** [intrnl/svelte-query#2]
Love the library!

It would be really nice to have a graphql example.
Also is it possible to config a global fetcher?

**Comment by intrnl** [comment]
You can query GraphQL like you'd do with regular HTTP fetching, though if you want more capabilities then I'd suggest using a more dedicated lib for it, such as [`svelte-apollo`](https://github.com/timhall/svelte-apollo)

As for configuring a global fetcher, you could wrap your app with `QueryConfigProvider` component, I should put this down on docs later (still have plenty to do)
```svelte
<script>
  import { QueryConfigProvider } from '@intrnl/svelte-query';

  function fetcher (url) {
    // [...]
  }

  let queryConfig = {
    queries: {
      queryFn: fetcher,
    },
  };
</script>

<QueryConfigProvider config={queryConfig}>
  <!-- The rest of your app -->
</QueryConfigProvider>
```

**Comment by galkatz373** [comment]
Thanks for the answer, I just heard many complaints about memory leak with apollo and svelte-apollo doesn't support skipping
