### ISSUE TITLE
Bug: not receiving error

### ISSUE THREAD

**Issue by iamyuu** [intrnl/svelte-query#3]
Hi! thanks for great library.
From example I'm get response from API like this:

```json
{
  "status_code": 401,
  "error_description": "The OAuth token you provided was invalid.",
  "error": "INVALID_AUTH"
}
```

But `status` is still the value for` loading` it should be ʻerror`, when I look in the terminal it gets an error like:

```
(node:77955) UnhandledPromiseRejectionWarning: ReferenceError: navigator is not defined
```

## environment

```
"@intrnl/svelte-query": "0.3.1",
"sapper": "0.28.10",
"svelte": "3.29.0",
```

**Comment by intrnl** [comment]
Can you provide a sandbox that can reproduce this issue?

**Comment by iamyuu** [comment]
You can use repo [svelteid/website](https://github.com/svelteid/website) to reproduce this issue

Step to reproduce:
- clone and checkout to branch `feat/event-page`
- install deps and rename `.env.example` to `.env`
- start dev server and go to page `/meetup`

**Comment by intrnl** [comment]
Ah, I haven't written a documentation about how server-side rendering works with this library, but on Sapper, it's something like this.

You need to provide initial data that will be used for the rendering by the server, if not, then it will try to check if it's online and then fetches the data by itself, which doesn't work since `navigator` isn't available on the server context.

```svelte
<script context='module'>
  import fetch from 'isomorphic-fetch';

  async function fetcher () {
    let resp = await fetch('https://api.github.com/repos/intrnl/svelte-query');
    if (!resp.ok) throw new Error(`HTTP error: ${resp.status}`);
    return resp.json();
  }

  export async function preload () {
    let initialData = await fetcher();
    return { initialData };
  }
</script>

<script>
  export let initialData;

  let q = query('repoData', fetcher, {
    initialData,
  });
</script>
```

**Comment by intrnl** [comment]
I'm planning to deprecate this library once the official one [lands](https://github.com/tanstack/svelte-query/pull/1) but until then I'd still be around maintaining this.
