### ISSUE TITLE
How to update cache?

### ISSUE THREAD

**Issue by omerman** [intrnl/svelte-query#4]
Hey Im Eager to use this lib, there is just one thing I couldn't figure out from the docs,

Could you share a recommended code snippet to set data for given key?

Thank you!

**Comment by intrnl** [comment]
Sorry that the docs aren't clear enough, I just haven't had the time to continue maintaining (especially when there's the [official adapter](https://github.com/tanstack/svelte-query) currently in WIP)

Regarding your question, are you perhaps trying to set the query data manually? [I believe this should help you](https://react-query.tanstack.com/docs/api/#querycachesetquerydata)

**Comment by omerman** [comment]
Oh Wow I didn't see the official adapter

So I guess I'll take a crack at the official package. thank you for referencing it.

Thank you for your quick response.
